"""add menu item and category tables

Revision ID: 6287fae76eed
Revises: ea5d1ee620b0
Create Date: 2026-07-02 16:23:08.067520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6287fae76eed'
down_revision = "e906f5c2f554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_categories_is_active', 'menu_categories', ['is_active'], unique=False)
    op.create_index('ix_menu_categories_position', 'menu_categories', ['position'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_items_category_id', 'menu_items', ['category_id'], unique=False)
    op.create_index('ix_menu_items_is_available', 'menu_items', ['is_available'], unique=False)
    op.create_index('ix_menu_items_position', 'menu_items', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_menu_items_position', table_name='menu_items')
    op.drop_index('ix_menu_items_is_available', table_name='menu_items')
    op.drop_index('ix_menu_items_category_id', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_menu_categories_position', table_name='menu_categories')
    op.drop_index('ix_menu_categories_is_active', table_name='menu_categories')
    op.drop_table('menu_categories')
    # ### end Alembic commands ###
