"""add_customer_requests_tables

Revision ID: 778c8485b0dd
Revises: eede4c89d4b6
Create Date: 2026-07-20 15:03:36.366997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '778c8485b0dd'
down_revision: Union[str, None] = 'eede4c89d4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('desired_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_requests_desired_datetime', 'customer_requests', ['desired_datetime'], unique=False)
    op.create_index(op.f('ix_customer_requests_status'), 'customer_requests', ['status'], unique=False)
    op.create_index('ix_customer_requests_status_request_type', 'customer_requests', ['status', 'request_type'], unique=False)
    op.create_table('customer_request_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_request_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_amount_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_currency_snapshot', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_request_id'], ['customer_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_request_items_customer_request_id'), 'customer_request_items', ['customer_request_id'], unique=False)
    op.create_index(op.f('ix_customer_request_items_menu_item_id'), 'customer_request_items', ['menu_item_id'], unique=False)
    op.drop_table('orders')
    op.drop_index('ix_order_items_menu_item_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('menu_item_title_snapshot', sa.VARCHAR(length=124), autoincrement=False, nullable=False),
    sa.Column('price_amount_snapshot', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('price_currency_snapshot', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='order_items_menu_item_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_menu_item_id', 'order_items', ['menu_item_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('total_price_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_price_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='orders_buyer_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.drop_index(op.f('ix_customer_request_items_menu_item_id'), table_name='customer_request_items')
    op.drop_index(op.f('ix_customer_request_items_customer_request_id'), table_name='customer_request_items')
    op.drop_table('customer_request_items')
    op.drop_index('ix_customer_requests_status_request_type', table_name='customer_requests')
    op.drop_index(op.f('ix_customer_requests_status'), table_name='customer_requests')
    op.drop_index('ix_customer_requests_desired_datetime', table_name='customer_requests')
    op.drop_table('customer_requests')
    # ### end Alembic commands ###
