"""create outbox and notification tables

Revision ID: e906f5c2f554
Revises: ea5d1ee620b0
Create Date: 2026-07-06 23:58:37.999399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e906f5c2f554'
down_revision: Union[str, None] = 'ea5d1ee620b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('customer_request_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'channel', 'recipient', name='uq_notification_deliveries_event_channel_recipient')
    )
    op.create_index(op.f('ix_notification_deliveries_customer_request_id'), 'notification_deliveries', ['customer_request_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_event_id'), 'notification_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_status'), 'notification_deliveries', ['status'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_aggregate_id'), 'outbox_messages', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_aggregate_type'), 'outbox_messages', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_messages_available_at'), 'outbox_messages', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_created_at'), 'outbox_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_event_id'), 'outbox_messages', ['event_id'], unique=True)
    op.create_index(op.f('ix_outbox_messages_event_type'), 'outbox_messages', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_messages_key'), 'outbox_messages', ['key'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_messages_topic'), 'outbox_messages', ['topic'], unique=False)
    op.create_table('processed_kafka_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('offset', sa.BigInteger(), nullable=False),
    sa.Column('consumer_group', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic', 'partition', 'offset', 'consumer_group', name='uq_processed_kafka_messages_offset')
    )
    op.create_index(op.f('ix_processed_kafka_messages_consumer_group'), 'processed_kafka_messages', ['consumer_group'], unique=False)
    op.create_index(op.f('ix_processed_kafka_messages_event_id'), 'processed_kafka_messages', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_kafka_messages_event_id'), table_name='processed_kafka_messages')
    op.drop_index(op.f('ix_processed_kafka_messages_consumer_group'), table_name='processed_kafka_messages')
    op.drop_table('processed_kafka_messages')
    op.drop_index(op.f('ix_outbox_messages_topic'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_key'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_event_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_event_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_created_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_available_at'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_aggregate_type'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_aggregate_id'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_notification_deliveries_status'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_customer_request_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
