all: 
  children:
    coffee_house:
      hosts:
        ubuntu-lab:
          ansible_host: 192.168.122.7
          ansible_user: reaper
          ansible_ssh_private_key_file: /home/reaper/.ssh/id_ed25519_devops_lab
          ansible_become_exe: /usr/bin/sudo.ws